{
  "type": "record",
  "name": "User",
  "namespace": "com.example.kafkastub.sample",
  "fields": [
    { "name": "id",        "type": "string" },
    { "name": "name",      "type": "string" },
    { "name": "email",     "type": "string" },
    { "name": "age",       "type": ["null", "int"], "default": null },
    { "name": "birthDate", "type": { "type": "int", "logicalType": "date" } },
    { "name": "createdAt", "type": { "type": "long", "logicalType": "timestamp-millis" } },
    { "name": "tags",      "type": { "type": "array", "items": "string" }, "default": [] }
  ]
}
